name: CheckLabels

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, '<can be merged>') 

name: Build and requirements

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r requirements.txt 
      - name: Run tests
        run: pip install httpx[cli] && pytest

name: Pytest

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: pip install httpx[cli] && pytest