name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install httpx
        run: pip install httpx[cli]
      - name: Create .env file
        run: |
          echo ${{ secrets.ENV_HOST }} >> .env
          echo ${{ vars.HOST }}
      - name: Run tests
        run: |
          echo ${{ secrets.ENV_HOST }} >> .env
          pytest