name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r requirements.txt && pip install httpx[cli]
      - name: Set up env
        run: |
          touch .env
          echo HOST=${{ secrets.HOST }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo USERNAME=${{ secrets.USERNAME }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env
          cat .env
      - name: Run tests
        run: pytest