name: Build

on:
  push:

jobs:

  CheckLabels:
    if: ${{ github.event.label.name == 'Can be merged' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check labels
      run: CheckLabels passed

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Push repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r requirements.txt 
      - name: Run tests
        run: pip install httpx[cli] && pytest
