name: labAPI CI/CD

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    step:
      - name: Push repo
        uses: actions/checkout@v4
      - name: Print hello
        run: echo "Hello world "